---
- name: register dotdeb key
  apt_key: url=http://www.dotdeb.org/dotdeb.gpg state=present

- name: add dotdeb default repositories
  apt_repository: repo='deb http://packages.dotdeb.org {{ debian.version }} all' state=present

- name: add dotdeb default sources repositories
  apt_repository: repo='deb-src http://packages.dotdeb.org {{ debian.version }} all' state=present

- name: install php packages
  apt: pkg={{ item }} state=latest
  with_items:
    - php7.0-cli
    - php7.0-fpm

- name: copy php.ini
  template: src=php.ini.j2 dest=/etc/php7/fpm/php.ini
  notify: restart php

- name: copy cli php.ini
  template: src=php.cli.ini.j2 dest=/etc/php7/cli/php.ini
