---
- name: register dotdeb key
  apt_key: url=http://www.dotdeb.org/dotdeb.gpg state=present
  when: use_dotdeb

- name: add dotdeb default repositories
  apt_repository: repo='deb http://packages.dotdeb.org {{ ansible_distribution_release }} all' state=present
  when: use_dotdeb

- name: add dotdeb default sources repositories
  apt_repository: repo='deb-src http://packages.dotdeb.org {{ ansible_distribution_release }} all' state=present
  when: use_dotdeb

- name: register sury key
  apt_key: url=https://packages.sury.org/php/apt.gpg state=present
  when: use_sury

- name: add sury default repositories
  apt_repository: repo='deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main' state=present
  when: use_sury

- name: install php packages
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - php{{ php.version }}-cli
      - php{{ php.version }}-fpm

- name: copy php.ini
  template: src=php.ini.j2 dest=/etc/php/{{ php.version }}/fpm/php.ini
  notify: restart php

- name: copy cli php.ini
  template: src=php.cli.ini.j2 dest=/etc/php/{{ php.version }}/cli/php.ini

- name: adjust user
  lineinfile: "dest=/etc/php/{{ php.version }}/fpm/pool.d/www.conf state=present regexp='^user =' line='user = {{ nginx.user }}'"

- name: adjust group
  lineinfile: "dest=/etc/php/{{ php.version }}/fpm/pool.d/www.conf state=present regexp='^group =' line='group = {{ nginx.user }}'"

- name: adjust listen
  lineinfile: "dest=/etc/php/{{ php.version }}/fpm/pool.d/www.conf state=present regexp='^listen =' line='listen = {{ php.fastcgi_pass }}'"

- name: adjust listen owner
  lineinfile: "dest=/etc/php/{{ php.version }}/fpm/pool.d/www.conf state=present regexp='^listen.owner = ' line='listen.owner = {{ nginx.user }}'"

- name: adjust listen group
  lineinfile: "dest=/etc/php/{{ php.version }}/fpm/pool.d/www.conf state=present regexp='^listen.group =' line='listen.group = {{ nginx.user }}'"
